brew "bash"
brew "bat"
brew "chafa"
brew "cloc"
brew "cmake"
brew "colima"
brew "coreutils"
brew "deno"
brew "diff-so-fancy"
brew "ffmpeg"
brew "fish"
brew "gd"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "gitlint"
brew "gnupg"
brew "go"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "lazygit"
brew "lsd"
brew "lua-language-server"
brew "mackup"
brew "mas"
brew "mods"
brew "moreutils"
brew "neovim"
brew "neovim-remote", link: false
brew "nmap"
brew "pam-reattach"
brew "pinentry-mac"
brew "python@3.11"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "telnet"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "universal-ctags"
brew "watch"
brew "wget"
brew "zsh"

cask "betterdisplay"
cask "brave-browser"
cask "chatgpt"
cask "discord"
cask "font-0xproto-nerd-font"
cask "imageoptim"
cask "keepingyouawake"
cask "notion"
cask "qlmarkdown"
cask "setapp"
cask "sketch"
cask "spotify"
cask "visual-studio-code"

mas "BetterJSON", id: 1511935951
mas "Boop", id: 1518425043
mas "HEIC Converter", id: 1294126402
mas "Magnet", id: 441258766
mas "Pixelmator Pro", id: 1289583905
mas "Userscripts-Mac-App", id: 1463298887
mas "Xcode", id: 497799835
