brew "mackup"
brew "mas"
brew "pinentry-mac"
brew "reattach-to-user-namespace"

cask "discord"
cask "docker"
cask "imageoptim"
cask "keepingyouawake"
cask "kitty"
cask "macfuse"
cask "qbittorrent"
cask "qlmarkdown"
cask "sketch"
cask "veracrypt"
cask "visual-studio-code"

mas "BetterJSON", id: 1511935951
mas "Boop", id: 1518425043
mas "Compressor", id: 424390742
mas "Deliveries", id: 924726344
mas "ExifPurge", id: 784466108
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Transmit", id: 1436522307
mas "Userscripts-Mac-App", id: 1463298887
mas "Xcode", id: 497799835
