################################################################################
# General
################################################################################

# Set default terminal to the one reported by the emulator
set -g default-terminal "$TERM"
set -g terminal-overrides ",$TERM:Tc"

# Allow passthru to enable image support in nvim
set -gq allow-passthrough on

# Set the prefix to ^A, like screen
unbind C-b
set -g prefix ^A
bind a send-prefix

# Bind : to command-prompt like vim
bind : command-prompt

# vi-style controls for copy mode
setw -g mode-keys vi
bind-key p paste-buffer
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Make it easier to enter copy mode
bind ^[ copy-mode

# Shorcuts for killing aspects of tmux
bind K confirm kill-server
bind X confirm kill-window

# Session management
bind C new-session

# Split preferences
bind ^\\ split-window -h -l 30% -c "#{pane_current_path}"

# Toggle last window like screen
bind ^a last-window

# Next/previous
bind C-n next-window
bind C-p previous-window

# Reload tmux config file with C-a /
bind / source-file ~/.tmux.conf

################################################################################
# User Interface
################################################################################

# Show status bar on top
set-option -g status-position top

# Start indexing from 1
set -g base-index 1
set -g pane-base-index 1

# ctrl+arrow word navigation
set-window-option -g xterm-keys on

# Autorename new tabs automatically
setw -g automatic-rename on

# Enable focus events
set-option -g focus-events on

# Enable mouse support
set -g mouse on

# Activity
setw -g monitor-activity on

################################################################################
# Plugins
################################################################################

# Rebind prefix to b
bind B set -g prefix ^b
bind A set -g prefix ^a

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin '2kabhishek/tmux2k'

# Configure tmux2k
set -g @tmux2k-theme 'catppuccin'
set -g @tmux2k-show-powerline true
set -g @tmux2k-left-plugins "session"
set -g @tmux2k-right-plugins "cpu ram battery time"
set -g @tmux2k-left-sep 
set -g @tmux2k-right-sep 

# Configure tmux-resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes '"~npm run "'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# Initializes TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# Automatically install plugins when tmux starts up if they aren't already installed
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
