export DOTFILES_LIB="$HOME/.lib"

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "$DOTFILES_LIB/init.zsh" ]]; then
  source "$DOTFILES_LIB/init.zsh"
fi
