export DOTFILES_LIB="$HOME/.lib"

if [[ -s "$HOME/.zprezto/init.zsh" ]]; then
  source "$HOME/.zprezto/init.zsh"
fi

if [[ -s "$DOTFILES_LIB/init.zsh" ]]; then
  source "$DOTFILES_LIB/init.zsh"
fi

export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"

export PATH="$VOLTA_HOME/bin:$PATH"
